language: java
script:
  - cd aula-01/java && mvn test javadoc:javadoc verify -P cobertura checkstyle:checkstyle pmd:pmd spotbugs:spotbugs
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jdk:
  - oraclejdk8